# Generated by Django 5.2.10 on 2026-01-09 08:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(max_length=500)),
                ('total_tweets', models.IntegerField(default=0)),
                ('relevant_tweets', models.IntegerField(default=0)),
                ('not_relevant_tweets', models.IntegerField(default=0)),
                ('percentage_relevant', models.FloatField(default=0.0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'datasets',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtendedDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('similarity_score', models.FloatField()),
                ('reference_word', models.CharField(max_length=255)),
                ('sentiment_value', models.FloatField()),
                ('polarity', models.CharField(max_length=10)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'extended_dictionary',
                'ordering': ['-similarity_score'],
            },
        ),
        migrations.CreateModel(
            name='SentimentDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('weight', models.FloatField()),
                ('polarity', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10)),
                ('source', models.CharField(default='base', max_length=50)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sentiment_dictionary',
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='SVMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('support_vectors', models.JSONField(default=list)),
                ('coefficients', models.JSONField(default=list)),
                ('intercept', models.FloatField(default=0.0)),
                ('train_accuracy', models.FloatField(default=0.0)),
                ('test_accuracy', models.FloatField(default=0.0)),
                ('trained_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'svm_models',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sentiment_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('all', 'All')], max_length=10)),
                ('top_words', models.JSONField(default=list)),
                ('word_weights', models.JSONField(default=dict)),
                ('document_distribution', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('confusion_matrix', models.JSONField(default=dict)),
                ('classification_report', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.svmmodel')),
            ],
            options={
                'db_table': 'evaluation_metrics',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('train_size', models.IntegerField()),
                ('test_size', models.IntegerField()),
                ('train_ratio', models.FloatField()),
                ('test_ratio', models.FloatField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataset')),
            ],
            options={
                'db_table': 'training_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('username', models.CharField(blank=True, max_length=255)),
                ('is_relevant', models.BooleanField(default=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='core.dataset')),
            ],
            options={
                'db_table': 'tweets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreprocessedTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('after_remove_punctuation', models.TextField(blank=True)),
                ('after_case_folding', models.TextField(blank=True)),
                ('after_cleaning', models.TextField(blank=True)),
                ('after_stopword', models.TextField(blank=True)),
                ('after_stemming', models.TextField(blank=True)),
                ('tokens', models.JSONField(default=list)),
                ('word_vectors', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tweet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessed', to='core.tweet')),
            ],
            options={
                'db_table': 'preprocessed_tweets',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_sentiment', models.CharField(max_length=10)),
                ('confidence_score', models.FloatField()),
                ('decision_value', models.FloatField()),
                ('predicted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.svmmodel')),
                ('tweet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='core.tweet')),
            ],
            options={
                'db_table': 'predictions',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10)),
                ('confidence', models.FloatField(default=1.0)),
                ('labeled_by', models.CharField(default='manual', max_length=50)),
                ('labeled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tweet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='core.tweet')),
            ],
            options={
                'db_table': 'labels',
            },
        ),
        migrations.CreateModel(
            name='FeatureVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighted_vector', models.JSONField(default=list)),
                ('pca_vector', models.JSONField(default=list)),
                ('original_dimension', models.IntegerField(default=300)),
                ('reduced_dimension', models.IntegerField(default=181)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tweet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_vector', to='core.tweet')),
            ],
            options={
                'db_table': 'feature_vectors',
            },
        ),
    ]
