# Generated by Django 5.2.10 on 2026-01-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurevector',
            name='original_dimension',
        ),
        migrations.RemoveField(
            model_name='featurevector',
            name='pca_vector',
        ),
        migrations.RemoveField(
            model_name='featurevector',
            name='reduced_dimension',
        ),
        migrations.RemoveField(
            model_name='featurevector',
            name='weighted_vector',
        ),
        migrations.AddField(
            model_name='featurevector',
            name='additional_features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='featurevector',
            name='negative_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='featurevector',
            name='polarity',
            field=models.CharField(default='neutral', max_length=10),
        ),
        migrations.AddField(
            model_name='featurevector',
            name='positive_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='featurevector',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='featurevector',
            name='tf_idf_vector',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='featurevector',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='featurevector',
            name='word_embedding',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='featurevector',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
