# Generated by Django 5.2.10 on 2026-01-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dataset_sampled_tweets_label_dataset_split_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocessedtweet',
            name='after_normalization',
            field=models.TextField(blank=True),
        ),
    ]
