# Generated by Django 5.2.10 on 2026-01-21 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_preprocessedtweet_after_normalization'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingStepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField(help_text='Nomor step training (3, 4, 4.5, 5, 6, 7)')),
                ('executed_at', models.DateTimeField(auto_now_add=True, help_text='Waktu eksekusi step')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_step_logs', to='core.dataset')),
            ],
            options={
                'verbose_name': 'Training Step Log',
                'verbose_name_plural': 'Training Step Logs',
                'ordering': ['step'],
                'unique_together': {('dataset', 'step')},
            },
        ),
    ]
