# Generated by Django 5.2.10 on 2026-01-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trainingsteplog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Label', 'verbose_name_plural': 'Labels'},
        ),
        migrations.AddField(
            model_name='label',
            name='predicted_sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], help_text='Predicted label by trained model (used for testing)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='confidence',
            field=models.FloatField(default=1.0, help_text='Prediction confidence (0–1)'),
        ),
        migrations.AlterField(
            model_name='label',
            name='labeled_by',
            field=models.CharField(default='manual', help_text='manual / svm / model', max_length=50),
        ),
        migrations.AlterField(
            model_name='label',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], help_text='Manual ground truth label (used for training)', max_length=10),
        ),
    ]
